In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
from nltk.tokenize import word_tokenize
import pandas as pd
import numpy as np

In [76]:
df_preprocessed = pd.read_csv('C:\\Users\\Janek\\Downloads\\df_train_preprocessed.csv')
df_preprocessed

Unnamed: 0                                       File  \
0               0  bb995ead-f65c-43e8-9d7f-771546d21651.tiff   
1               1  2a476c78-ce1c-4535-831c-626635b69fef.tiff   
2               2  7bbd6936-4f3d-4eb4-bb75-983cbca08f48.tiff   
3               3  62d852b8-25eb-48e0-8cfe-0091c4f2453e.tiff   
4               4  8c5a5c2b-c58d-4f7e-985d-236bcc69011e.tiff   
...           ...                                        ...   
10824       10824   3827a69b-52cb-4600-a970-5163322ac4d7.jpg   
10825       10825   671cca7a-fe43-4743-9c23-4c4a4ef5b810.jpg   
10826       10826   a09e8f97-35c0-4327-9ab8-dfc2b2052722.jpg   
10827       10827   42ede5e5-8b9c-48d7-8996-ca81e8408b90.jpg   
10828       10828   c76876e7-1df3-4e1e-8898-cbdb7d44df72.jpg   

                                                    Text        Category  \
0      ['parliament', 'wsrdd', 'scrambeer', 'engeyi',...   advertisement   
1      ['gilvvmather', 'insertion', 'order', 'i6ken7n...   advertisement   
2      ['newport', '902', 'cosmopolitan', 'april', '1...   advertisement   
3      ['goforthegołd', 'introduce', 'true', 'gqld', ...   advertisement   
4      ['what', 's', 'tobacoo', 'induisty', 'dong', '...   advertisement   
...                                                  ...             ...   
10824  ['umowa', '0', 'dzielo', 'kukulowo', '0625', '...  umowa_o_dzielo   
10825  ['umowa', 'odiflo', 'zawrzeć', 'dzień', '20221...  umowa_o_dzielo   
10826  ['uowaodiflo', 'zawrzeć', 'dzień', '2020032', ...  umowa_o_dzielo   
10827  ['umowa', '0', 'dziłlo', 'zawrzeć', 'dzień', '...  umowa_o_dzielo   
10828  ['umowa', '0', 'dzieło', 'zawrzeć', 'dzień', '...  umowa_o_dzielo   

      language  
0           en  
1           en  
2           en  
3           en  
4           en  
...        ...  
10824       pl  
10825       pl  
10826       pl  
10827       pl  
10828       pl  

[10829 rows x 5 columns]

In [77]:
from sklearn.preprocessing import LabelEncoder
Encoder = LabelEncoder()
df_preprocessed['Category'] = Encoder.fit_transform(df_preprocessed['Category'])

In [78]:
df_preprocessed

Unnamed: 0                                       File  \
0               0  bb995ead-f65c-43e8-9d7f-771546d21651.tiff   
1               1  2a476c78-ce1c-4535-831c-626635b69fef.tiff   
2               2  7bbd6936-4f3d-4eb4-bb75-983cbca08f48.tiff   
3               3  62d852b8-25eb-48e0-8cfe-0091c4f2453e.tiff   
4               4  8c5a5c2b-c58d-4f7e-985d-236bcc69011e.tiff   
...           ...                                        ...   
10824       10824   3827a69b-52cb-4600-a970-5163322ac4d7.jpg   
10825       10825   671cca7a-fe43-4743-9c23-4c4a4ef5b810.jpg   
10826       10826   a09e8f97-35c0-4327-9ab8-dfc2b2052722.jpg   
10827       10827   42ede5e5-8b9c-48d7-8996-ca81e8408b90.jpg   
10828       10828   c76876e7-1df3-4e1e-8898-cbdb7d44df72.jpg   

                                                    Text  Category language  
0      ['parliament', 'wsrdd', 'scrambeer', 'engeyi',...         0       en  
1      ['gilvvmather', 'insertion', 'order', 'i6ken7n...         0       en  
2      ['newport', '902', 'cosmopolitan', 'april', '1...         0       en  
3      ['goforthegołd', 'introduce', 'true', 'gqld', ...         0       en  
4      ['what', 's', 'tobacoo', 'induisty', 'dong', '...         0       en  
...                                                  ...       ...      ...  
10824  ['umowa', '0', 'dzielo', 'kukulowo', '0625', '...        19       pl  
10825  ['umowa', 'odiflo', 'zawrzeć', 'dzień', '20221...        19       pl  
10826  ['uowaodiflo', 'zawrzeć', 'dzień', '2020032', ...        19       pl  
10827  ['umowa', '0', 'dziłlo', 'zawrzeć', 'dzień', '...        19       pl  
10828  ['umowa', '0', 'dzieło', 'zawrzeć', 'dzień', '...        19       pl  

[10829 rows x 5 columns]

In [79]:
from sklearn.model_selection import train_test_split
df_train, df_val = train_test_split(df_preprocessed, test_size=0.2, random_state=42)

In [80]:
X_train = df_train['Text']
y_train = df_train['Category']
X_val = df_val['Text']
y_val = df_val['Category']
X_train_tokens= [str(word_tokenize(entry)) for entry in X_train]
Tfidf_vect = TfidfVectorizer(max_features=5000)
Tfidf_vect.fit(X_train_tokens)
Train_X_Tfidf = Tfidf_vect.transform(X_train)
Val_X_Tfidf = Tfidf_vect.transform(X_val)

## Naive Bayes

In [81]:
def training_pipeline_bayes(Train_X_Tfidf, Val_X_Tfidf, y_val):
    Naive = naive_bayes.MultinomialNB()
    Naive.fit(Train_X_Tfidf, y_train)
    predictions_NB = Naive.predict(Val_X_Tfidf)
    accuracy = accuracy_score(predictions_NB, y_val)
    f1 = f1_score(predictions_NB, y_val, average='macro')
    print("Naive Bayes Accuracy Score:", accuracy * 100)
    print("Naive Bayes F1 Score:", f1 * 100)
    return predictions_NB

In [82]:
training_pipeline_bayes(Train_X_Tfidf, Val_X_Tfidf, y_val)

Naive Bayes Accuracy Score: 67.12834718374884
Naive Bayes F1 Score: 68.75839993855612


array([ 6,  5,  5, ..., 14, 10,  5])

## SVM

In [85]:
def training_pipeline_svm(Train_X_Tfidf, Val_X_Tfidf, y_val):
    SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
    SVM.fit(Train_X_Tfidf,y_train)
    predictions_SVM = SVM.predict(Val_X_Tfidf)
    accuracy = accuracy_score(predictions_SVM, y_val)
    f1 = f1_score(predictions_SVM, y_val, average='macro')
    precision = precision_score(predictions_SVM, y_val, average='macro')
    recall = recall_score(predictions_SVM, y_val, average='macro')
    confusion_mat = confusion_matrix(predictions_SVM, y_val)
    confusion_df = pd.DataFrame(confusion_mat, columns=np.unique(y_val), index=np.unique(y_val))
    print("SVM Accuracy Score:", accuracy * 100)
    print("SVM:", f1 * 100)
    print("SVM Precision:", precision * 100)
    print("SVM Recall:", recall * 100)
    print("Confusion Matrix:")
    print(confusion_df)
    return predictions_SVM

In [86]:
training_pipeline_svm(Train_X_Tfidf, Val_X_Tfidf, y_val)

SVM Accuracy Score: 72.80701754385966
SVM: 75.45862478683715
SVM Precision: 75.50137923799596
SVM Recall: 77.02780316543621
Confusion Matrix:
    0   1   2   3   4   5   6   7   8   9   ...  11  12  13   14  15  16  17  \
0   52   1   2   2   0   6   0   1   0   3  ...   0   5   2    0   0   4   0   
1    6  71   3   3   4   2  17   1   3   6  ...   0   6   3    1   0   5   2   
2    2   0  91   1   0   0   0   1   3   0  ...   0   4   0    0   0   0   0   
3   29   9   2  96   6  19   6   1   1   7  ...   0  21   3    1   4  14   5   
4    1   1   1   0  60   1   4   6   2   0  ...   0   3   4    0   0   8   3   
5   15   3   1   3   6  92   5   5   1   7  ...   0   4   8    0   2   7   6   
6    1   7   0   0   5   1  73   4   1   1  ...   0   0   3    0   0   4   0   
7    0   0   5   0   2   2   0  66   5   0  ...   0   4   5    0   1   2   0   
8    0   3   5   1   0   1   0  17  72   2  ...   0   2   1    1   0   4   1   
9    5   2   0   0   0   1   0   1   0  71  ...   0   7   

array([ 6,  3,  3, ..., 16, 10,  5])

bezbledne fitowanie:
-umowa_sprzedazy_samochodu 
-umowa_o_dzielo 
-umowa_na_odleglosc_odstapienie 
-pozwolenie_uzytkowanie_obiektu_budowlanego

## XGBoost

In [87]:
import xgboost as xgb

def training_pipeline_xgb(Train_X_Tfidf, Val_X_Tfidf, y_val):    
    xgb_model = xgb.XGBClassifier()
    xgb_model.fit(Train_X_Tfidf, y_train)
    
    predictions_xgb = xgb_model.predict(Val_X_Tfidf)
    accuracy = accuracy_score(predictions_xgb, y_val)
    f1 = f1_score(predictions_xgb, y_val, average='macro')
    
    print("XGBoost Accuracy Score:", accuracy * 100)
    print("XGBoost F1 Score:", f1 * 100)
    
    return predictions_xgb

In [89]:
training_pipeline_xgb(Train_X_Tfidf, Val_X_Tfidf, y_val)

C:\Users\Janek\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[01:24:55] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGBoost Accuracy Score: 69.71375807940905
XGBoost F1 Score: 72.44792115047309


array([ 1,  3,  3, ...,  3, 10,  5])

## LinearSVC

In [90]:
from sklearn.svm import LinearSVC

def training_pipeline_linear(Train_X_Tfidf, Val_X_Tfidf, y_val):    
    linear_model = LinearSVC()
    linear_model.fit(Train_X_Tfidf, y_train)
    
    predictions_linear = linear_model.predict(Val_X_Tfidf)
    accuracy = accuracy_score(predictions_linear, y_val)
    f1 = f1_score(predictions_linear, y_val, average='macro')
    
    print("Linear Classifier Accuracy Score:", accuracy * 100)
    print("Linear Classifier F1 Score:", f1 * 100)
    
    return predictions_linear

In [91]:
training_pipeline_linear(Train_X_Tfidf, Val_X_Tfidf, y_val)

Linear Classifier Accuracy Score: 71.37580794090489
Linear Classifier F1 Score: 73.74887330222634


array([ 6,  3,  3, ..., 14, 10,  6])

## Random Forest

In [92]:
from sklearn.ensemble import RandomForestClassifier

def training_pipeline_rf(Train_X_Tfidf, Val_X_Tfidf, y_val):
    rf_model = RandomForestClassifier()
    rf_model.fit(Train_X_Tfidf, y_train)
    
    predictions_rf = rf_model.predict(Val_X_Tfidf)
    accuracy = accuracy_score(predictions_rf, y_val)
    f1 = f1_score(predictions_rf, y_val, average='macro')
    
    print("Random Forest Accuracy Score:", accuracy * 100)
    print("Random Forest F1 Score:", f1 * 100)
    
    return predictions_rf

In [93]:
training_pipeline_rf(Train_X_Tfidf, Val_X_Tfidf, y_val)

Random Forest Accuracy Score: 69.62142197599262
Random Forest F1 Score: 72.21017976314799


array([ 4,  3,  3, ..., 14, 10,  5])

## Logistic Regression

In [96]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

def training_pipeline_lr(Train_X_Tfidf, Val_X_Tfidf, y_val):
    LR = LogisticRegression()
    LR.fit(Train_X_Tfidf, y_train)
    predictions_LR = LR.predict(Val_X_Tfidf)
    accuracy = accuracy_score(predictions_LR, y_val)
    f1 = f1_score(predictions_LR, y_val, average='macro')
    precision = precision_score(predictions_LR, y_val, average='macro')
    recall = recall_score(predictions_LR, y_val, average='macro')
    confusion_mat = confusion_matrix(predictions_LR, y_val)
    
    # Convert confusion matrix to DataFrame for better visualization
    confusion_df = pd.DataFrame(confusion_mat, columns=np.unique(y_val), index=np.unique(y_val))
    
    print("Logistic Regression Accuracy Score:", accuracy * 100)
    print("Logistic Regression F1 Score:", f1 * 100)
    print("Logistic Regression Precision:", precision * 100)
    print("Logistic Regression Recall:", recall * 100)
    
    return predictions_LR

In [97]:
training_pipeline_lr(Train_X_Tfidf, Val_X_Tfidf, y_val)

Logistic Regression Accuracy Score: 72.25300092336103
Logistic Regression F1 Score: 74.75140738891875
Logistic Regression Precision: 74.94686982977707
Logistic Regression Recall: 76.20092476825808


array([ 6,  3,  3, ...,  3, 10,  5])

# Top 2 logistic regression i SVM